"use client";
import Image from "next/image";
import { useCallback, useEffect, useMemo, useState } from "react";
import { subscribeToSupabaseBroadcast } from "@/src/shared/realtime/supabase-broadcast";
import styles from "./page.module.css";
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const requestLabels = { pendente: "Aguardando atendimento", aceito: "Pedido aceito", cancelado: "Pedido recusado" };
export default function TableOrderClient({ token }) {
  const [data, setData] = useState(null); const [session, setSession] = useState(undefined); const [activeCategory, setActiveCategory] = useState(null); const [cart, setCart] = useState({}); const [notes, setNotes] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const loadSession = useCallback(async () => { const response = await fetch(`/api/public/tables/${token}/session`, { cache: "no-store" }); const body = await response.json(); if (response.ok) setSession(body.data); }, [token]);
  useEffect(() => { let active = true; Promise.all([fetch(`/api/public/tables/${token}`, { cache: "no-store" }), fetch(`/api/public/tables/${token}/session`, { cache: "no-store" })]).then(async ([menuResponse, sessionResponse]) => { const menuBody = await menuResponse.json(); const sessionBody = await sessionResponse.json(); if (!active) return; if (!menuResponse.ok) { setMessage(menuBody?.error?.message || "Mesa indisponível."); setSession(null); return; } setData(menuBody.data); setActiveCategory(menuBody.data.categories?.[0]?.id ?? null); setSession(sessionResponse.ok ? sessionBody.data : null); }).catch(() => { if (active) { setMessage("Não foi possível carregar esta mesa."); setSession(null); } }); return () => { active = false; }; }, [token]);
  useEffect(() => {
    if (!session || session.status !== "ativo") return;
    let unsubscribe = () => {};
    unsubscribe = subscribeToSupabaseBroadcast({ channel: "renascer:comanda", onChange: loadSession });
    return () => unsubscribe();
  }, [loadSession, session]);
  const visibleProducts = useMemo(() => (data?.products ?? []).filter((product) => !activeCategory || product.category_id === activeCategory), [activeCategory, data]);
  const selectedItems = useMemo(() => (data?.products ?? []).filter((product) => cart[product.id]).map((product) => ({ ...product, quantity: cart[product.id] })), [cart, data]);
  const knownSubtotal = selectedItems.reduce((sum, item) => sum + (item.pricing_mode === "variable" ? 0 : item.price * item.quantity), 0); const itemCount = selectedItems.reduce((sum, item) => sum + item.quantity, 0);
  function changeQuantity(id, delta) { setCart((current) => { const next = { ...current }; const quantity = Math.max(0, (next[id] || 0) + delta); if (quantity) next[id] = quantity; else delete next[id]; return next; }); }
  async function identify(event) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); try { const response = await fetch(`/api/public/tables/${token}/session`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), whatsapp: form.get("whatsapp") }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Não foi possível entrar nesta mesa."); setSession({ ...body.data, name: body.data.customer_name, joinedAt: body.data.joined_at, requests: [] }); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function submitOrder() { if (!selectedItems.length || busy) return; setBusy(true); setMessage(""); try { const response = await fetch(`/api/public/tables/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ notes, items: selectedItems.map((item) => ({ productId: item.id, quantity: item.quantity })) }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Não foi possível enviar o pedido."); setCart({}); setNotes(""); setMessage("Pedido enviado. A equipe já recebeu sua solicitação."); await loadSession(); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  if (!data || session === undefined) return <main className={styles.center}><section className={styles.welcome}><span>PADARIA RENASCER</span><h1>{message || "Preparando sua mesa..."}</h1><p>Estamos validando o QR Code e carregando o cardápio.</p></section></main>;
  if (!session) return <main className={styles.center}><section className={styles.welcome}><div className={styles.tableBadge}>Mesa {data.table.tableNumber}</div><span>BEM-VINDO À RENASCER</span><h1>Seu pedido começa aqui.</h1><p>Informe seu nome para acessar o cardápio e acompanhar seus pedidos nesta mesa.</p>{message && <div className={styles.message} role="alert">{message}</div>}<form onSubmit={identify} className={styles.identifyForm}><label>Nome <b>*</b><input name="name" autoComplete="name" required minLength="2" maxLength="100" placeholder="Como podemos chamar você?" /></label><label>WhatsApp <small>(opcional)</small><input name="whatsapp" autoComplete="tel" inputMode="tel" maxLength="30" placeholder="(51) 99999-9999" /></label><button disabled={busy}>{busy ? "Entrando..." : "Ver cardápio"}</button></form></section></main>;
  if (session.status === "encerrado") return <main className={styles.center}><section className={styles.welcome}><div className={styles.closedMark}>✓</div><span>MESA {data.table.tableNumber}</span><h1>Comanda encerrada.</h1><p>Obrigado pela visita. Para iniciar um novo atendimento, leia novamente o QR Code após a liberação da mesa.</p></section></main>;
  return <main className={styles.page}><header className={styles.header}><div><span>MESA {data.table.tableNumber}</span><h1>Olá, {(session.name || session.customer_name)?.split(" ")[0]}.</h1><p>Escolha seus produtos e envie quando estiver pronto.</p></div><div className={styles.openStatus}><i /> Comanda aberta</div></header>{message && <div className={styles.message} role="status">{message}</div>}
    <nav className={styles.categories} aria-label="Categorias do cardápio">{data.categories.map((category) => <button type="button" key={category.id} className={activeCategory === category.id ? styles.activeCategory : ""} onClick={() => setActiveCategory(category.id)}>{category.name}</button>)}</nav>
    <div className={styles.layout}><section className={styles.menu}><div className={styles.sectionTitle}><div><span>CARDÁPIO INTERNO</span><h2>{data.categories.find((category) => category.id === activeCategory)?.name || "Produtos"}</h2></div><small>{visibleProducts.length} produto(s)</small></div><div className={styles.products}>{visibleProducts.map((product) => <article key={product.id}>{product.image_url && <Image src={product.image_url} alt={product.name} width={96} height={96} unoptimized />}<div className={styles.productBody}><small>{product.unit}</small><h3>{product.name}</h3><p>{product.description || "Preparado com o cuidado da Padaria Renascer."}</p><strong>{product.pricing_mode === "variable" ? "Valor após pesagem" : money.format(product.price)}</strong></div><div className={styles.quantity}><button type="button" aria-label={`Remover ${product.name}`} onClick={() => changeQuantity(product.id, -1)}>−</button><span>{cart[product.id] || 0}</span><button type="button" aria-label={`Adicionar ${product.name}`} onClick={() => changeQuantity(product.id, 1)}>+</button></div></article>)}</div></section>
      <aside className={styles.orderPanel}><div className={styles.orderTitle}><div><span>SEU PEDIDO</span><strong>{itemCount ? `${itemCount} item(ns)` : "Carrinho vazio"}</strong></div><b>{money.format(knownSubtotal)}</b></div>{selectedItems.length ? <ul>{selectedItems.map((item) => <li key={item.id}><div><strong>{item.quantity}× {item.name}</strong><small>{item.pricing_mode === "variable" ? "Valor confirmado após pesagem" : money.format(item.price * item.quantity)}</small></div><button type="button" onClick={() => changeQuantity(item.id, -item.quantity)}>Remover</button></li>)}</ul> : <p className={styles.empty}>Toque no botão + dos produtos para montar seu pedido.</p>}<label className={styles.notes}>Observações<textarea rows="3" maxLength="300" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Ex.: sem açúcar, aquecer, cortar ao meio" /></label><div className={styles.total}><span>Subtotal conhecido</span><strong>{money.format(knownSubtotal)}</strong></div><button className={styles.send} type="button" disabled={busy || !selectedItems.length} onClick={submitOrder}>{busy ? "Enviando..." : "Enviar pedido"}</button>{selectedItems.some((item) => item.pricing_mode === "variable") && <small className={styles.weightNote}>Produtos por peso terão o valor informado pela equipe antes da aceitação.</small>}</aside></div>
    {(session.requests?.length ?? 0) > 0 && <section className={styles.history}><div className={styles.sectionTitle}><div><span>ACOMPANHAMENTO</span><h2>Seus pedidos</h2></div></div><div className={styles.requestGrid}>{session.requests.map((request) => <article key={request.id} data-status={request.status}><div><strong>{requestLabels[request.status]}</strong><small>{new Date(request.created_at).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</small></div><ul>{request.items.map((item) => <li key={item.id}><span>{item.quantity}× {item.product_name}</span><span>{item.pricing_mode === "variable" && !item.unit_price ? "A pesar" : money.format(item.subtotal)}</span></li>)}</ul>{request.status === "cancelado" && <p>{request.items.find((item) => item.cancellation_reason)?.cancellation_reason || "A equipe não pôde atender este pedido."}</p>}</article>)}</div></section>}
  </main>;
}
