"use client";
import { useEffect, useMemo, useState } from "react";
import styles from "./page.module.css";
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
export default function TableOrderClient({ token }) {
  const [data, setData] = useState(null); const [cart, setCart] = useState({}); const [name, setName] = useState(""); const [notes, setNotes] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/public/tables/${token}`, { cache: "no-store" }).then(async (response) => ({ ok: response.ok, body: await response.json() })).then(({ ok, body }) => { if (ok) setData(body.data); else setMessage(body?.error?.message || "Mesa indisponível."); }); }, [token]);
  const items = useMemo(() => (data?.products ?? []).filter((item) => cart[item.id]).map((item) => ({ ...item, quantity: cart[item.id] })), [cart, data]);
  const fixedTotal = items.reduce((sum, item) => sum + (item.pricing_mode === "variable" ? 0 : item.price * item.quantity), 0);
  function quantity(id, delta) { setCart((current) => { const next = { ...current }; const value = Math.max(0, (next[id] || 0) + delta); if (value) next[id] = value; else delete next[id]; return next; }); }
  async function submit(event) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch(`/api/public/tables/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customerName: name, notes, items: items.map((item) => ({ productId: item.id, quantity: item.quantity })) }) }); const body = await response.json(); if (response.ok) { setCart({}); setNotes(""); setMessage(`Pedido enviado para a Mesa ${body.data.table_number}. Aguarde o atendimento.`); } else setMessage(body?.error?.message || "Não foi possível enviar."); setBusy(false); }
  if (!data) return <main className={styles.page}><div className={styles.card}><h1>Renascer</h1><p>{message || "Carregando cardápio da mesa..."}</p></div></main>;
  return <main className={styles.page}><header><span>PADARIA RENASCER</span><h1>Mesa {data.table.tableNumber}</h1><p>Escolha seus produtos. Itens por peso terão o valor confirmado pelo atendente após a pesagem.</p></header>{message && <div className={styles.message}>{message}</div>}<form onSubmit={submit}><section className={styles.products}>{data.products.map((product) => <article key={product.id}><div><small>{product.unit}</small><strong>{product.name}</strong><p>{product.description}</p><b>{product.pricing_mode === "variable" ? "Valor após pesagem" : money.format(product.price)}</b></div><div className={styles.qty}><button type="button" onClick={() => quantity(product.id, -1)}>−</button><span>{cart[product.id] || 0}</span><button type="button" onClick={() => quantity(product.id, 1)}>+</button></div></article>)}</section><aside className={styles.cart}><h2>Seu pedido</h2><label>Seu nome (opcional)<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Observações<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows="3" /></label><div><span>Subtotal conhecido</span><strong>{money.format(fixedTotal)}</strong></div><button disabled={busy || items.length === 0}>{busy ? "Enviando..." : "Enviar pedido"}</button></aside></form></main>;
}
