const LEVEL_L={1:{data:19,ecc:7,align:[]},2:{data:34,ecc:10,align:[6,18]},3:{data:55,ecc:15,align:[6,22]},4:{data:80,ecc:20,align:[6,26]},5:{data:108,ecc:26,align:[6,30]}};
function gfMultiply(x,y){let z=0;for(let i=7;i>=0;i-=1){z=(z<<1)^((z>>>7)*0x11d);if((y>>>i)&1)z^=x;}return z&255;}
function polynomialMultiply(a,b){const result=new Array(a.length+b.length-1).fill(0);for(let i=0;i<a.length;i+=1)for(let j=0;j<b.length;j+=1)result[i+j]^=gfMultiply(a[i],b[j]);return result;}
function rsGenerator(degree){let generator=[1],root=1;for(let i=0;i<degree;i+=1){generator=polynomialMultiply(generator,[1,root]);root=gfMultiply(root,2);}return generator;}
function rsRemainder(data,degree){const generator=rsGenerator(degree),result=new Array(degree).fill(0);for(const byte of data){const factor=byte^result[0];result.shift();result.push(0);for(let i=0;i<degree;i+=1)result[i]^=gfMultiply(generator[i+1],factor);}return result;}
function appendBits(bits,value,length){for(let i=length-1;i>=0;i-=1)bits.push((value>>>i)&1);}
function chooseVersion(byteLength){for(let version=1;version<=5;version+=1){if(4+8+byteLength*8<=LEVEL_L[version].data*8)return version;}throw new Error("URL longa demais para o QR Code da mesa.");}
function encodeCodewords(text,version){const bytes=[...new TextEncoder().encode(text)],info=LEVEL_L[version],bits=[];appendBits(bits,0b0100,4);appendBits(bits,bytes.length,8);bytes.forEach((byte)=>appendBits(bits,byte,8));const capacity=info.data*8;for(let i=0;i<Math.min(4,capacity-bits.length);i+=1)bits.push(0);while(bits.length%8)bits.push(0);const data=[];for(let i=0;i<bits.length;i+=8){let byte=0;for(let j=0;j<8;j+=1)byte=(byte<<1)|bits[i+j];data.push(byte);}let pad=0;while(data.length<info.data){data.push(pad%2===0?0xec:0x11);pad+=1;}return [...data,...rsRemainder(data,info.ecc)];}
function formatBits(data){let value=data<<10;const generator=0x537,generatorDegree=31-Math.clz32(generator);while(31-Math.clz32(value)>=generatorDegree)value^=generator<<(31-Math.clz32(value)-generatorDegree);return((data<<10)|value)^0x5412;}
function setFinder(matrix,row,col){const size=matrix.length;for(let dr=-1;dr<=7;dr+=1)for(let dc=-1;dc<=7;dc+=1){const r=row+dr,c=col+dc;if(r<0||r>=size||c<0||c>=size)continue;const inside=dr>=0&&dr<=6&&dc>=0&&dc<=6;matrix[r][c]=Boolean(inside&&(dr===0||dr===6||dc===0||dc===6||(dr>=2&&dr<=4&&dc>=2&&dc<=4)));}}
function setAlignment(matrix,centerRow,centerCol){if(matrix[centerRow][centerCol]!==null)return;for(let dr=-2;dr<=2;dr+=1)for(let dc=-2;dc<=2;dc+=1)matrix[centerRow+dr][centerCol+dc]=Math.max(Math.abs(dr),Math.abs(dc))!==1;}
function setupBase(version){const size=21+4*(version-1),matrix=Array.from({length:size},()=>Array(size).fill(null));setFinder(matrix,0,0);setFinder(matrix,size-7,0);setFinder(matrix,0,size-7);for(const row of LEVEL_L[version].align)for(const col of LEVEL_L[version].align)setAlignment(matrix,row,col);for(let i=8;i<size-8;i+=1){if(matrix[i][6]===null)matrix[i][6]=i%2===0;if(matrix[6][i]===null)matrix[6][i]=i%2===0;}const format=formatBits(1<<3),getBit=(index)=>((format>>>index)&1)!==0;for(let i=0;i<=5;i+=1)matrix[i][8]=getBit(i);matrix[7][8]=getBit(6);matrix[8][8]=getBit(7);matrix[8][7]=getBit(8);for(let i=9;i<15;i+=1)matrix[8][14-i]=getBit(i);for(let i=0;i<8;i+=1)matrix[8][size-1-i]=getBit(i);for(let i=8;i<15;i+=1)matrix[size-15+i][8]=getBit(i);matrix[size-8][8]=true;return matrix;}
export function makeQrMatrix(text){const value=String(text),bytes=new TextEncoder().encode(value),version=chooseVersion(bytes.length),codewords=encodeCodewords(value,version),bits=[];codewords.forEach((byte)=>appendBits(bits,byte,8));const matrix=setupBase(version),size=matrix.length;let bitIndex=0,upward=true;for(let col=size-1;col>0;col-=2){if(col===6)col-=1;for(let step=0;step<size;step+=1){const row=upward?size-1-step:step;for(let offset=0;offset<2;offset+=1){const currentCol=col-offset;if(matrix[row][currentCol]!==null)continue;let bit=bitIndex<bits.length?bits[bitIndex]:0;bitIndex+=1;if((row+currentCol)%2===0)bit^=1;matrix[row][currentCol]=Boolean(bit);}}upward=!upward;}return matrix;}
export function qrSvgString(text,scale=10,border=4){const matrix=makeQrMatrix(text),size=(matrix.length+border*2)*scale;let path="";matrix.forEach((row,r)=>row.forEach((dark,c)=>{if(dark)path+=`M${(c+border)*scale} ${(r+border)*scale}h${scale}v${scale}h-${scale}z`;}));return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="white"/><path d="${path}" fill="black"/></svg>`;}
