"use client";
import { useCallback,useEffect,useMemo,useState } from "react";import { subscribeToSupabaseBroadcast } from "@/src/shared/realtime/supabase-broadcast";import { formatCommandCode } from "@/src/shared/formatters/command-code";import styles from "./AdminOperations.module.css";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});const TITLES={orders:["Pedidos","Acompanhe todas as vendas em um só lugar."],finance:["Financeiro","Entradas, saídas e despesas reais da operação."],suppliers:["Fornecedores","Contatos e parceiros comerciais da padaria."],reports:["Relatórios","Uma leitura direta do desempenho da padaria."],audit:["Auditoria","Quem fez, quando fez e o que mudou."]};const ACTIONS={"sale.created":"Venda criada","command.requested":"Pedido de mesa recebido","command.closed":"Comanda fechada","delivery.accepted":"Delivery aceito","supplier.created":"Fornecedor cadastrado","supplier.updated":"Fornecedor atualizado","finance.expense_created":"Despesa registrada","sale.canceled":"Venda cancelada","sale.item_canceled":"Item cancelado"};
export default function AdminOperations({view}){const[data,setData]=useState(view==="reports"?null:[]);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[channel,setChannel]=useState("");const[type,setType]=useState("");const[search,setSearch]=useState("");const[editing,setEditing]=useState(null);const[suppliers,setSuppliers]=useState([]);
 const load=useCallback(async()=>{setLoading(true);const url=view==="suppliers"?"/api/admin/suppliers":`/api/admin/operations?view=${view}${channel?`&channel=${channel}`:""}${type?`&type=${type}`:""}`;try{const response=await fetch(url,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message||"Não foi possível carregar os dados.");setData(body.data);}catch(error){setMessage(error.message);}finally{setLoading(false);}},[channel,type,view]);
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer);},[load]);useEffect(()=>{if(view!=="finance")return;fetch("/api/admin/suppliers",{cache:"no-store"}).then((r)=>r.json()).then((b)=>setSuppliers(b.data||[]));},[view]);
 useEffect(()=>{if(view!=="orders")return;const cleanups=["renascer:delivery","renascer:comanda"].map((realtimeChannel)=>subscribeToSupabaseBroadcast({channel:realtimeChannel,onChange:load}));return()=>cleanups.forEach((cleanup)=>cleanup());},[load,view]);
 async function saveSupplier(event){event.preventDefault();const form=new FormData(event.currentTarget);const payload={name:form.get("name"),document:form.get("document"),contactName:form.get("contactName"),phone:form.get("phone"),email:form.get("email"),notes:form.get("notes"),active:editing?.active??true};const response=await fetch(editing?`/api/admin/suppliers/${editing.id}`:"/api/admin/suppliers",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();if(!response.ok){setMessage(body?.error?.message||"Não foi possível salvar.");return;}event.currentTarget.reset();setEditing(null);setMessage("Fornecedor salvo.");load();}
 async function toggleSupplier(item){await fetch(`/api/admin/suppliers/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:item.name,document:item.document,contactName:item.contact_name,phone:item.phone,email:item.email,notes:item.notes,active:!item.active})});load();}
 async function saveExpense(event){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:form.get("description"),amount:form.get("amount"),category:form.get("category"),paymentMethod:form.get("paymentMethod"),supplierId:form.get("supplierId")||null})});const body=await response.json();if(!response.ok){setMessage(body?.error?.message||"Não foi possível registrar.");return;}event.currentTarget.reset();setMessage("Despesa registrada.");load();}
 const filtered=useMemo(()=>{if(!Array.isArray(data)||!search)return data;const term=search.toLocaleLowerCase("pt-BR");return data.filter((item)=>JSON.stringify(item).toLocaleLowerCase("pt-BR").includes(term));},[data,search]);const title=TITLES[view];
 return <div className={styles.page}><header><span>GESTÃO DA PADARIA</span><h1>{title[0]}</h1><p>{title[1]}</p></header>{message&&<div className={styles.message}>{message}</div>}
  {(view==="orders"||view==="finance"||view==="audit")&&<div className={styles.filters}><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Buscar nos registros" />{view==="orders"&&<select value={channel} onChange={(e)=>setChannel(e.target.value)}><option value="">Todos os canais</option><option value="delivery">Delivery</option><option value="pos">Caixa</option><option value="comanda">Comandas</option></select>}{view==="finance"&&<select value={type} onChange={(e)=>setType(e.target.value)}><option value="">Entradas e saídas</option><option value="entrada">Entradas</option><option value="saida">Saídas</option></select>}<button onClick={load}>Atualizar</button></div>}
  {view==="finance"&&<form className={styles.form} onSubmit={saveExpense}><h2>Registrar despesa</h2><input name="description" required placeholder="Descrição"/><input name="amount" required inputMode="decimal" placeholder="Valor"/><input name="category" placeholder="Categoria (ex.: insumos)"/><select name="paymentMethod"><option value="dinheiro">Dinheiro</option><option value="pix">Pix</option><option value="debito">Débito</option><option value="credito">Crédito</option></select><select name="supplierId"><option value="">Sem fornecedor</option>{suppliers.filter((item)=>item.active).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button>Registrar saída</button></form>}
  {view==="suppliers"&&<><form className={styles.form} onSubmit={saveSupplier}><h2>{editing?"Editar fornecedor":"Novo fornecedor"}</h2><input name="name" defaultValue={editing?.name||""} key={`name-${editing?.id}`} required placeholder="Nome do fornecedor"/><input name="document" defaultValue={editing?.document||""} key={`doc-${editing?.id}`} placeholder="CNPJ ou documento"/><input name="contactName" defaultValue={editing?.contact_name||""} key={`contact-${editing?.id}`} placeholder="Pessoa de contato"/><input name="phone" defaultValue={editing?.phone||""} key={`phone-${editing?.id}`} placeholder="Telefone"/><input name="email" defaultValue={editing?.email||""} key={`email-${editing?.id}`} placeholder="E-mail"/><input name="notes" defaultValue={editing?.notes||""} key={`notes-${editing?.id}`} placeholder="Observações"/><button>{editing?"Salvar alterações":"Cadastrar fornecedor"}</button>{editing&&<button type="button" className={styles.secondary} onClick={()=>setEditing(null)}>Cancelar</button>}</form><section className={styles.cards}>{(data||[]).map((item)=><article key={item.id}><div><small>{item.active?"ATIVO":"INATIVO"}</small><h3>{item.name}</h3><p>{item.contact_name||"Sem contato informado"}</p><span>{item.phone||item.email||item.document||"Complete os dados deste fornecedor"}</span></div><div><button onClick={()=>setEditing(item)}>Editar</button><button className={styles.secondary} onClick={()=>toggleSupplier(item)}>{item.active?"Desativar":"Ativar"}</button></div></article>)}</section></>}
  {loading&&<p className={styles.empty}>Carregando registros reais...</p>}
  {!loading&&view==="orders"&&<section className={styles.cards}>{(filtered||[]).map((item)=><article key={item.id}><div><small>{item.channel==="comanda"?formatCommandCode(item.order_number):`#${item.order_number}`} · {item.channel}</small><h3>{item.command_label||item.customer?.name||"Venda de balcão"}</h3><p>{item.status.replaceAll("_"," ")} · {new Date(item.created_at).toLocaleString("pt-BR")}</p><span>{item.items.length} item(ns)</span></div><strong>{money.format(item.total)}</strong></article>)}</section>}
  {!loading&&view==="finance"&&<><section className={styles.metrics}><div><span>Entradas exibidas</span><strong>{money.format((filtered||[]).filter((i)=>i.type==="entrada"&&i.status==="confirmado").reduce((s,i)=>s+i.amount,0))}</strong></div><div><span>Saídas exibidas</span><strong>{money.format((filtered||[]).filter((i)=>i.type==="saida"&&i.status==="confirmado").reduce((s,i)=>s+i.amount,0))}</strong></div></section><section className={styles.ledger}>{(filtered||[]).map((item)=><article key={item.id} data-type={item.type}><div><strong>{item.description||item.category}</strong><small>{item.supplier?.name||item.payment_method||"Sem forma informada"} · {new Date(item.occurred_at).toLocaleString("pt-BR")}</small></div><b>{item.type==="saida"?"−":"+"} {money.format(item.amount)}</b></article>)}</section></>}
  {!loading&&view==="reports"&&data&&<><section className={styles.metrics}><div><span>Faturamento</span><strong>{money.format(data.revenue)}</strong></div><div><span>Despesas</span><strong>{money.format(data.expenses)}</strong></div><div><span>Resultado</span><strong>{money.format(data.balance)}</strong></div><div><span>Ticket médio</span><strong>{money.format(data.averageTicket)}</strong></div></section><section className={styles.reportGrid}><article><h2>Vendas por canal</h2>{Object.entries(data.channels).map(([name,value])=><div className={styles.row} key={name}><span>{name} · {value.count}</span><strong>{money.format(value.total)}</strong></div>)}</article><article><h2>Produtos mais vendidos</h2>{data.topProducts.map((item)=><div className={styles.row} key={item.name}><span>{item.name}</span><strong>{item.quantity}</strong></div>)}</article></section></>}
  {!loading&&view==="audit"&&<section className={styles.ledger}>{(filtered||[]).map((item)=><article key={item.id}><div><strong>{ACTIONS[item.action]||item.action}</strong><small>{item.employee?.full_name||item.actor_kind||"Sistema"} · {new Date(item.created_at).toLocaleString("pt-BR")}</small></div><span>{item.entity_type}{item.entity_id?` · ${item.entity_id.slice(0,8)}`:""}</span></article>)}</section>}
  {!loading&&Array.isArray(filtered)&&filtered.length===0&&view!=="suppliers"&&<p className={styles.empty}>Nenhum registro real encontrado para este filtro.</p>}
 </div>}
