create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'operador' check (role in ('admin', 'operador')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  category_id uuid references public.categories(id) on delete set null,
  name text not null,
  slug text not null unique,
  description text,
  price numeric(10, 2) not null check (price >= 0),
  unit text not null default 'un',
  image_path text,
  featured boolean not null default false,
  active boolean not null default true,
  stock_control boolean not null default false,
  stock_quantity numeric(12, 3) not null default 0 check (stock_quantity >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  customer_id uuid not null references public.customers(id) on delete restrict,
  status text not null default 'pendente' check (
    status in ('pendente', 'confirmado', 'em_preparo', 'pronto', 'saiu_entrega', 'concluido', 'cancelado')
  ),
  fulfillment_type text not null check (fulfillment_type in ('entrega', 'retirada')),
  payment_method text not null check (payment_method in ('dinheiro', 'pix', 'credito', 'debito')),
  payment_status text not null default 'pendente' check (
    payment_status in ('pendente', 'pago', 'estornado', 'cancelado')
  ),
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0),
  total numeric(10, 2) not null check (total >= 0),
  change_for numeric(10, 2),
  address_street text,
  address_number text,
  address_neighborhood text,
  address_complement text,
  address_reference text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  created_at timestamptz not null default now()
);

create table public.financial_transactions (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id) on delete set null,
  type text not null check (type in ('entrada', 'saida')),
  category text not null,
  description text,
  amount numeric(12, 2) not null check (amount >= 0),
  payment_method text,
  status text not null default 'pendente' check (status in ('pendente', 'confirmado', 'cancelado')),
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.store_settings (
  id smallint primary key default 1 check (id = 1),
  store_name text not null default 'Padaria e Confeitaria Renascer',
  accepts_orders boolean not null default true,
  delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0),
  minimum_order numeric(10, 2) not null default 0 check (minimum_order >= 0),
  delivery_estimate_min integer not null default 35 check (delivery_estimate_min >= 0),
  delivery_estimate_max integer not null default 45 check (delivery_estimate_max >= delivery_estimate_min),
  pickup_estimate_min integer not null default 25 check (pickup_estimate_min >= 0),
  pickup_estimate_max integer not null default 35 check (pickup_estimate_max >= pickup_estimate_min),
  whatsapp text,
  updated_at timestamptz not null default now()
);

insert into public.store_settings (id)
values (1)
on conflict (id) do nothing;

create index categories_active_sort_idx on public.categories(active, sort_order);
create index products_category_active_sort_idx on public.products(category_id, active, sort_order);
create index products_featured_active_idx on public.products(featured, active);
create index orders_status_created_idx on public.orders(status, created_at desc);
create index orders_customer_created_idx on public.orders(customer_id, created_at desc);
create index order_items_order_idx on public.order_items(order_id);
create index financial_transactions_occurred_idx on public.financial_transactions(occurred_at desc);
create index audit_logs_entity_idx on public.audit_logs(entity_type, entity_id, created_at desc);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger customers_set_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

create trigger financial_transactions_set_updated_at
before update on public.financial_transactions
for each row execute function public.set_updated_at();

create trigger store_settings_set_updated_at
before update on public.store_settings
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.financial_transactions enable row level security;
alter table public.audit_logs enable row level security;
alter table public.store_settings enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'produtos',
  'produtos',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.create_order_transaction(
  p_customer jsonb,
  p_order jsonb,
  p_items jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_customer_id uuid;
  v_order public.orders;
begin
  insert into public.customers (name, phone)
  values (
    p_customer->>'name',
    p_customer->>'phone'
  )
  on conflict (phone) do update
  set
    name = excluded.name,
    updated_at = now()
  returning id into v_customer_id;

  insert into public.orders (
    customer_id,
    fulfillment_type,
    payment_method,
    subtotal,
    delivery_fee,
    total,
    change_for,
    address_street,
    address_number,
    address_neighborhood,
    address_complement,
    address_reference,
    notes
  )
  values (
    v_customer_id,
    p_order->>'fulfillment_type',
    p_order->>'payment_method',
    (p_order->>'subtotal')::numeric,
    coalesce((p_order->>'delivery_fee')::numeric, 0),
    (p_order->>'total')::numeric,
    nullif(p_order->>'change_for', '')::numeric,
    p_order#>>'{address,street}',
    p_order#>>'{address,number}',
    p_order#>>'{address,neighborhood}',
    p_order#>>'{address,complement}',
    p_order#>>'{address,reference}',
    p_order->>'notes'
  )
  returning * into v_order;

  insert into public.order_items (
    order_id,
    product_id,
    product_name,
    unit_price,
    quantity,
    subtotal
  )
  select
    v_order.id,
    (item->>'product_id')::uuid,
    item->>'product_name',
    (item->>'unit_price')::numeric,
    (item->>'quantity')::integer,
    (item->>'subtotal')::numeric
  from jsonb_array_elements(p_items) as item;

  return jsonb_build_object(
    'id', v_order.id,
    'order_number', v_order.order_number,
    'status', v_order.status,
    'payment_status', v_order.payment_status,
    'created_at', v_order.created_at
  );
end;
$$;

revoke execute on function public.create_order_transaction(jsonb, jsonb, jsonb) from public;
revoke execute on function public.create_order_transaction(jsonb, jsonb, jsonb) from anon;
revoke execute on function public.create_order_transaction(jsonb, jsonb, jsonb) from authenticated;
grant execute on function public.create_order_transaction(jsonb, jsonb, jsonb) to service_role;
